services:
  gitrest:
    build:
      context: .
      target: runner
    ports:
      - "3000:3000"
    volumes:
      - git:/home/node/documents
    restart: always
volumes:
  git:
    driver: local
