name: "push-tag-create-release"

on:
  push:
    tags:
      - "*_v*"

jobs:
  release-metadata:
    name: Get release metadata
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # ratchet:actions/checkout@v3
        with:
          fetch-depth: "0" # all history
          persist-credentials: false
      - uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd # ratchet:pnpm/action-setup@v2
        with:
          version: "^7"
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # ratchet:actions/setup-node@v3
        with:
          node-version: "16"
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml

      - name: Install Fluid build tools
        run: |
          corepack enable
          pnpm add --global @fluid-tools/build-cli@0.16.0-0

          # Info for debugging
          which flub
          flub --help
          flub commands
      - name: Get release metadata JSON
        run: |
          $(flub release fromTag ${{ github.ref }} --json | jq -c) > release-metadata.json
      - name: Upload release metadata JSON
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # ratchet:actions/upload-artifact@v3
        with:
          name: release-metadata
          path: release-metadata.json
          retention-days: 3
      - name: Load release metadata env variable
        run: |
          echo "RELEASE_JSON=$(cat release-metadata.json)" >> $GITHUB_ENV
      - name: Set releaseType output variable
        run: |
         echo "releaseType=${{ fromJson(env.RELEASE_JSON).packageOrReleaseGroup }}" >> "$GITHUB_OUTPUT"

      # Generate release reports
      - name: Check out tag
        run: |
          git checkout ${{ github.ref }}
      - name: Create release reports (manifests)
        run: |
          mkdir reports
          flub release report -g ${{ fromJson(env.RELEASE_JSON).packageOrReleaseGroup }} -o reports
      - name: Upload release reports
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # ratchet:actions/upload-artifact@v3
        with:
          name: release-reports
          path: reports
          retention-days: 7

      # Generate changelog
      - name: Generate changelog
        # This changelog is only for client patch releases
        if: fromJson(env.RELEASE_JSON).releaseType == 'patch' && fromJson(env.RELEASE_JSON).packageOrReleaseGroup == 'client'
        run: |
          # starting and ending versions are the same because we want to generate a changelog for a single release
          pnpm exec auto-changelog \
          --starting-version ${{ fromJson(env.RELEASE_JSON).tag }} \
          --ending-version ${{ fromJson(env.RELEASE_JSON).tag }} \
          --tag-prefix ${{ fromJson(env.RELEASE_JSON).packageOrReleaseGroup }}_v \
          --output auto-changelog.md \
          --template changelog.hbs

      # This should be calculated outside the workflow eventually. Maybe in flub release fromTag.
      - name: Set release title (client)
        if: fromJson(env.RELEASE_JSON).packageOrReleaseGroup == 'client'
        run: |
          echo "RELEASE_TITLE=Fluid Framework v${{ fromJson(env.RELEASE_JSON).version }} (${{
          fromJson(env.RELEASE_JSON).releaseType }})" >> $GITHUB_ENV
      - name: Set release title
        if: fromJson(env.RELEASE_JSON).packageOrReleaseGroup != 'client'
        run: |
          echo "RELEASE_TITLE=${{ fromJson(env.RELEASE_JSON).packageOrReleaseGroup }} v${{ fromJson(env.RELEASE_JSON).version }} (${{ fromJson(env.RELEASE_JSON).releaseType }})" >> $GITHUB_ENV

      - name: Create GH release
        # Only enabled for client
        if: fromJson(env.RELEASE_JSON).packageOrReleaseGroup == 'client'
        uses: ncipollo/release-action@main
        with:
          # Allow updates to existing releases.
          allowUpdates: true

          # Will skip if a published (non-draft) release already exists.
          skipIfReleaseExists: true

          # Leave the release as a draft so that the release engineer can verify it before it's public. Once we are
          # more confident in the automation, we may update this workflow to publish the release as well.
          draft: true
          omitDraftDuringUpdate: true # don't change the draft state when updating

          # Created in "Set release title" step
          name: ${{ env.RELEASE_TITLE }}
          omitNameDuringUpdate: false # always overwrite the name

          # Created in "Generate changelog" step
          bodyFile: auto-changelog.md
          omitBodyDuringUpdate: true # Don't overwrite the body

          artifacts: "reports/*.*"
          artifactErrorsFailBuild: true
          tag: ${{ fromJson(env.RELEASE_JSON).tag }}
